sudo: false
language: ruby

# Need Boost 1.55, which isn't in the 12.04 repositories - install from a PPA.
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-log1.55-dev
      - libboost-date-time1.55-dev
      - libboost-thread1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-locale1.55-dev
      - libboost-iostreams1.55-dev
      - g++-5

install: wget https://github.com/loot/loot/releases/download/v0.8.0/metadata-validator.tar.gz -O - | tar -xz

script: ./metadata-validator $TRAVIS_BUILD_DIR/masterlist.yaml

notifications:
  irc:
    channels:
      - "chat.freenode.net#loot"
    use_notice: true
    skip_join: true
